[package]
name = "team_queue_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = "0.12"
tokio = { version = "1", features = ["full"] }
rand = "0.8"
dotenv = "0.15"
async-trait = "0.1.88"
